config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resource :auth, only: [] do
    get :signin,  action: :new
    get :signout, action: :destroy
    get ':provider/callback', action: :create, as: :callback
  end

  resources :repos, constraints: { name: /[^\/]+/}, only: [:new, :create, :show] do
    collection do
      get ':service/:organization/:name', to: 'repos#show', as: 'long'
      get ':service/:organization/:name/:id', to: 'builds#show', as: 'build'

      post ':service/:organization/:name/webhook', to: 'repos#webhook', as: 'webhook'
      post ':service/:organization/:name/follow', to: 'repos#follow', as: 'follow'
      post ':service/:organization/:name/unfollow', to: 'repos#unfollow', as: 'unfollow'
      post ':service/:organization/:name/build', to: 'repos#build', as: 'build_head'
    end
  end

  resources :builds, only: [:show]
  resources :users, only: [:show] do
    collection do
      post :sync, to: 'users#sync'
    end
  end
end

Rails.application.routes.url_helpers.module_eval do
  def repo_path(repo, options = {})
    long_repos_path(
      repo[:service],
      repo[:organization],
      repo[:name],
      options
    )
  end

  def repo_url(repo, options = {})
    long_repos_url(
      repo[:service],
      repo[:organization],
      repo[:name],
      options
    )
  end
end

app/models/build.rb
class Build < ActiveRecord::Base
  enum status: [ :queued, :success, :pending, :failure, :error ]

  STATUS_HIERARCHY = [:error, :failure, :pending, :queued, :success]

  belongs_to :repo
  has_many :build_logs

  belongs_to :parent, foreign_key: :parent_id, class_name: Build
  has_many :children, foreign_key: :parent_id, class_name: Build

  def short_sha
    self.sha.first(7) if self.sha
  end

  def enqueue!
    Delayed::Job.enqueue BuildJob.new(self)
  end

  def overall_status
    statuses = children_statuses << self.status
    statuses.uniq!
    STATUS_HIERARCHY.each do |status|
      return status.to_s if statuses.include?(status.to_s)
    end
    return self.status
  end

  def children_statuses
    self.children.map do |child|
      child.overall_status
    end
  end

  def overall_completed_at
    completed_ats = children_completed_at << self.completed_at
    return nil if completed_ats.any? { |c| c.nil? }
    completed_ats.max
  end

  def children_completed_at
    self.children.map(&:overall_completed_at)
  end

  def self.new_from_config(config, parent)
    repo = config.repo ? Repo.find_by(config.repo) : parent.repo
    return nil unless repo

    Build.new(
      parent: parent,
      env: config.env.to_json,
      parallel: config.parallel,
      # TODO this should find_or_create_by
      # TODO what happens when this is a public repo?
      # TODO can we differentiate the two effectively
      repo: repo,
      branch: config.branch,
      sha: config.sub_project_path ? parent.sha : nil,
      sub_project_path: config.sub_project_path,
    )
  end
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_filter :require_session, only: [:show]
  before_filter :load_build, only: [:show]
  before_filter :require_repo_permissions, only: [:show]

  def show
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
  include FontAwesome::Rails::IconHelper

  def build_status(status)
    case status
    when 'pending'
      content_tag :span, data: {toggle: 'tooltip', 'original-title': 'in progress', placement: 'right'} do
        fa_icon "cog spin fw"
      end
    when 'queued'
      content_tag :span, data: {toggle: 'tooltip', 'original-title': 'queued', placement: 'right'} do
        fa_icon "clock-o fw"
      end
    when 'success'
      content_tag :span, data: {toggle: 'tooltip', 'original-title': 'success', placement: 'right'} do
        fa_icon "check fw", class: 'text-success'
      end
    when 'failure'
      content_tag :span, data: {toggle: 'tooltip', 'original-title': 'failure', placement: 'right'} do
        fa_icon "times fw", class: 'text-danger'
      end
    else
      content_tag :span, data: {toggle: 'tooltip', 'original-title': 'error', placement: 'right'} do
        fa_icon "exclamation-triangle fw", class: 'text-danger'
      end
    end
  end

  def build_duration(started_at, completed_at)
    return "N/A" unless started_at
    distance_of_time_in_words(started_at, completed_at || Time.now, include_seconds: true)
  end
end

app/views/builds/_build.html.haml
- repo = build.repo
- path = build_repos_path(repo.to_params.symbolize_keys.merge(id: build.id))
%tr
  %td= link_to build.id, path
  %td= link_to repo.short_name, repo_path(repo)
  %td= link_to build.branch, path
  %td= link_to build.short_sha || "N/A", path
  %td= link_to build.created_at, path
  %td= build_duration(build.started_at, build.completed_at)
  %td= link_to build_status(build.status), path

app/views/builds/_collection.html.haml
%table.table.table-striped.table-hover.no-highlights
  %tr
    %th #
    %th Repo
    %th Branch
    %th SHA
    %th Created
    %th Duration
    %th

  = render builds

app/views/builds/_tree.html.haml
%ul.tree
  - builds.each do |build|
    - repo = build.repo
    - path = build_repos_path(repo.to_params.symbolize_keys.merge(id: build.id))
    - sub_project_or_repo = build.sub_project_path || build.repo.short_name
    %li
      = link_to path do
        = build_status(build.status)
        = sub_project_or_repo
      - if build.children.present?
        -#TODO nice little N+1 query you got there
        = render partial: "tree", locals: {builds: build.children}

app/views/builds/show.html.haml
.col-md-20.col-sm-24.col-lg-16.col-centered
  = render 'flash'

  %legend Build Show

  %dl.dl-horizontal
    %dt ID
    %dd= @build.id

    %dt Branch
    %dd= @build.branch

    %dt SHA
    %dd= @build.short_sha

    %dt Created
    %dd= @build.created_at

    %dt Overall Status
    %dd
      = build_status(@build.overall_status)

    %dt Overall Duration
    %dd= build_duration(@build.started_at, @build.overall_completed_at)

    %dt Build Status
    %dd= build_status(@build.status)

    %dt Started
    %dd= @build.started_at || "N/A"

    %dt Completed
    %dd= @build.completed_at || "N/A"

    %dt Duration
    %dd= build_duration(@build.started_at, @build.completed_at)

    %dt Git
    %dd= link_to @repo.external_url, @repo.external_url

    %dt All builds
    %dd= link_to @repo.builds.count, repo_path(@repo)

    %dt BuildTree
    %dd= render partial: "tree", locals: {builds: [@build]}

  %legend Build Log

  - @build.build_logs.each do |log|
    - panel_class = log.exit_code == 0 ? "panel-success" : "panel-danger"
    .panel{class: panel_class}
      .panel-heading
        %h5= log.cmd

      .panel-body
        - JSON.parse(log.text).each do |io_line|
          - type, line = io_line.first
          - if type == 'stdout'
            %span= line
            %br
          - else
            %span.text-danger= line
            %br