config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resource :auth, only: [] do
    get :signin,  action: :new
    get :signout, action: :destroy
    get ':provider/callback', action: :create, as: :callback
  end

  resources :repos, constraints: { name: /[^\/]+/}, only: [:new, :create, :show] do
    collection do
      get ':service/:organization/:name', to: 'repos#show', as: 'long'
      get ':service/:organization/:name/:id', to: 'builds#show', as: 'build'

      post ':service/:organization/:name/webhook', to: 'repos#webhook', as: 'webhook'
      post ':service/:organization/:name/follow', to: 'repos#follow', as: 'follow'
      post ':service/:organization/:name/unfollow', to: 'repos#unfollow', as: 'unfollow'
      post ':service/:organization/:name/build', to: 'repos#build', as: 'build_head'
    end
  end

  resources :builds, only: [:show]
  resources :users, only: [:show] do
    collection do
      post :sync, to: 'users#sync'
    end
  end
end

Rails.application.routes.url_helpers.module_eval do
  def repo_path(repo, options = {})
    long_repos_path(
      repo[:service],
      repo[:organization],
      repo[:name],
      options
    )
  end

  def repo_url(repo, options = {})
    long_repos_url(
      repo[:service],
      repo[:organization],
      repo[:name],
      options
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  rescue StandardError
    nil
  end

  def logged_in?
    !!current_user
  end

  private

  def require_repo_permissions
    unless authorized_for_repo?(@repo)
      raise ActionController::RoutingError.new('Not Found')
    end
  end

  def authorized_for_repo?(repo)
    user_repos.any? do |user_repo_api_resp|
      user_repo = Repo.initialize_by_api(user_repo_api_resp)
      repo == user_repo
    end
  end

  def require_session
    unless logged_in?
      flash[:error] ||= []
      flash[:error] << "Please log in"
      redirect_to signin_auth_path
    end
  end

  def user_repos
    Rails.cache.fetch(user_repos_key, expires_in: 24.hours) do
      GitApi.new(current_user).repos
    end
  end

  def user_repos_key
    "user_repos_#{current_user.slug}"
  end

  def load_repo
    if params[:id]
      @repo = Repo.find(params[:id])
    else
      @repo = Repo.find_by!(
        :service => params[:service],
        :organization => params[:organization],
        :name => params[:name]
      )
    end
  end

  def load_build
    if params[:id]
      @build = Build.find(params[:id])
      @repo = @build.repo
    end
  end

  def redirect_with_error(path, error)
    flash[:error] ||= []
    flash[:error] << error
    redirect_to path
  end

  def render_422
    render json: {error: 422}, status: 422
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include FontAwesome::Rails::IconHelper
end

app/views/application/_flash.html.haml
- content_for :flash_display, true

- flash.each do |type, messages|
  - messages = [messages] unless messages.is_a?(Array)
  - messages.each do |message|
    .alert.alert-dismissable{class: "alert-#{type}"}
      %button.close{type:"button", 'data-dismiss' => "alert"}
        = fa_icon 'times'
      %h4.no-vertical-margins
        = message

app/views/application/_nav.html.haml
.navbar.navbar-default.navbar-static-top{role: 'navigation'}
  .container-fluid
    .navbar-header
      %button.navbar-toggle{'data-toggle' => 'collapse', 'data-target' => '.navbar-collapse'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        -#Swanky Logo Goes Here
        BT
    .navbar-collapse.collapse
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to 'Dashboard', user_path(current_user)
          %li= link_to 'Add Repo', new_repo_path
          %li= link_to 'Sign Out', signout_auth_path
          %li
            = link_to user_path(current_user), class: 'nav-image' do
              = image_tag current_user.avatar, class: 'img-circle'
        - else
          %li= link_to 'Sign In', signin_auth_path